### ISSUE TITLE
Use Lambda Container

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/terraform-aws-postman-test-lambda#30]
If we use a Lambda container, then user's Terraform plan won't be muddied by the source code has of this Lambda changing. We would have to store it in an ECR repo accessible by all, though, similar to the DB migration Lambda.

**Comment by mzroth** [comment]
Resolved by [pr#35](https://github.com/byu-oit/terraform-aws-postman-test-lambda/pull/35)
